### ISSUE TITLE
system application needs to be protected?

### ISSUE THREAD

**Issue by ycd2016** [GZOSP-Devices/device_oneplus_oneplus3#1]
I am sorry for disturbing you. I try to give my own Oneplus3 compilation failed. It compiled about 75% then appears to be due to "system application needs to be protected". I accidentally close off the window and forget the screenshot. Could you tell me how to solve it?

**Comment by ycd2016** [comment]
I'm trying to recompile.
```
  HOST_ARCH = x86_64
  HOST_OS = linux
  HOST_BUILD_TYPE = release
  HOST_OS_EXTRA = Linux-4.4.0-91-generic-x86_64-with-Ubuntu-16.04-xenial
  OUT_DIR = /gzosp/out
  PLATFORM_VERSION_CODENAME = REL
  PLATFORM_VERSION = 8.0.0
  GZOSP_VERSION = Gzosp-oneplus3-8.0.Alpha.1.0-UNOFFICIAL-20170930-2134
  TARGET_PRODUCT = gzosp_oneplus3
  TARGET_BUILD_VARIANT = userdebug
  TARGET_BUILD_TYPE = release
  TARGET_ARCH = arm64
  TARGET_ARCH_VARIANT = armv8-a
  TARGET_CPU_VARIANT = kryo
  TARGET_GCC_VERSION = 4.9
  TARGET_KERNEL_TOOLCHAIN = 4.9
```

**Comment by Martinusbe** [comment]
i have just now compiled it fine

**Comment by ycd2016** [comment]
Thank you. It's being recompiled. There is no error so far.

**Comment by ycd2016** [comment]
The current error is memory limit exceeded (I have 8G, enough?). I will try to increase memory size tomorrow.
