### ISSUE TITLE
Hangs on splash screen 

### ISSUE THREAD

**Issue by IronSharpensIron2717** [GZOSP-Devices/device_oneplus_oneplus3#2]
Do you have op3 booting on gzosp 8.1? My build hangs on splash screen

**Comment by Martinusbe** [comment]
yea it boots, are you decrypted

**Comment by IronSharpensIron2717** [comment]
Hmm, yes I'm decrypted, are you using the dependinces listed in the 8.1 branch? If so guess I'll run another build and see.

**Comment by Martinusbe** [comment]
well, i'm using oppo common and vendor 8.1, but that shouldn't matter for op3.
make sure you have staging/8.1 kernel tho

**Comment by IronSharpensIron2717** [comment]
Fresh sync and still no boot, mine is 3t do you think that has something to do with it?
