### ISSUE TITLE
android.hidl.base@1.0.so missing and no known rule to make it

### ISSUE THREAD

**Issue by ycd2016** [GZOSP-Devices/device_oneplus_oneplus3#3]
Happy new year. Actually I‘m builing ValidusOs. (8.1, oneplus3)
![image](https://user-images.githubusercontent.com/18079718/34466284-d9ce3bea-ef08-11e7-8df6-c44d4b429d7f.png)
I didn't find much useful information. It seems to be Treble's file?

**Comment by Martinusbe** [comment]
https://github.com/GZOSP-Devices/device_oneplus_oneplus3/commit/089e2bbbaf1622de34aafd504c66e26fbba48622

this will be needed again now
but i have to rework the op3 trees, been busy with 5t

**Comment by ycd2016** [comment]
Thanks, I know what to do now.
