### ISSUE TITLE
missing libgptutils

### ISSUE THREAD

**Issue by ycd2016** [GZOSP-Devices/device_oneplus_oneplus3#4]
Error in hardware/qcom/bootctrl/Android.mk
Seems AOSP's problem, I'm rolling back to the prev release.
`hardware/qcom/bootctrl/Android.mk: error: bootctrl.msm8996 (SHARED_LIBRARIES android-arm64) missing libgptutils (SHARED_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/core/main.mk:728: error: exiting from previous errors.
16:07:01 ckati failed with: exit status 1
build/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1
make: Leaving directory '/aosp'
#### make failed to build some targets (30 seconds) ####
`

**Comment by Martinusbe** [comment]
i will be updating the tree today
probably

**Comment by ycd2016** [comment]
![image](https://user-images.githubusercontent.com/18079718/34641030-981fff2e-f338-11e7-9116-0a456289863c.png)
Thanks. After I considered [these files](https://github.com/OnePlusOSS/android_device_qcom_common/tree/oneplus3/6.0.1/recovery/oem-recovery), I've built it successfully.

**Comment by ycd2016** [comment]
Unfortunately, hangs on the Oneplus logo......

**Comment by ycd2016** [comment]
Strangely, solved after just recompiled.

**Comment by be-neth** [comment]
> Unfortunately, hangs on the Oneplus logo......

Do you have traces of the hang ? Logcat is enable very early now, and can display early crashes.

I just tried a fresh gzosp build for oneplus 3 branch 8.1 and my phone do not display anything after android logo.
I have a crash that I can report.

> Strangely, solved after just recompiled.

You are lucky :p, but does not work for me :(

@Martinusbe : Can we open new issue regarding build error here, on github ? Or do you work with another bug tracking system ?

**Comment by Martinusbe** [comment]
use the display hal on my git for now, default branch, i need to fix that stuff with new hal.
my builds boot fine
